builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X main.Version={{.Version}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: pete911
    name: ipcalc
brews:
  - repository:
      owner: pete911
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    name: ipcalc
    homepage: "https://github.com/pete911/ipcalc"
    description: "IP calculator"
    folder: Formula
    install: |
      bin.install "ipcalc"
    test: |
      assert_match /version/, shell_output("#{bin}/ipcalc", 0)
